# Generated by Django 3.2.5 on 2022-02-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220221_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeaccount',
            name='file',
        ),
    ]
