# Generated by Django 3.2.12 on 2022-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_salesmanagementcrc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmanagementcrc',
            options={'ordering': ['-upload_datetime']},
        ),
        migrations.AddField(
            model_name='salesmanagementcrc',
            name='yearmonth',
            field=models.CharField(default=202206, max_length=32, verbose_name='年月'),
            preserve_default=False,
        ),
    ]
