# Generated by Django 3.2.12 on 2022-06-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220624_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesManagementACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=32, verbose_name='文件名')),
                ('filepath', models.CharField(max_length=32, verbose_name='文件路径')),
                ('yearmonth', models.CharField(max_length=32, verbose_name='年月')),
                ('upload_datetime', models.DateTimeField(verbose_name='上传时间')),
                ('upload_person', models.CharField(max_length=32, verbose_name='上传人')),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
    ]
